# Start ExplorViz
# Monitored applications can be connected

version: "3.2"
services:

  reverse-proxy:
    image: explorviz/reverse-proxy:production
    container_name: explorviz-reverse-proxy
    depends_on:
      - authentication
      - landscape
      - discovery
    ports:
      - "8080:8080"

  mongo:
    image: mongo
    container_name: explorviz-backend-auth-mongo
    volumes:
       - explorviz-auth-mongo-data:/data/db
       - explorviz-auth-mongo-configdb:/data/configdb

  authentication:
    image: explorviz/explorviz-backend-authentication:latest
    container_name: explorviz-backend-auth
    depends_on:
      - mongo
    environment:
      - MONGO_IP=mongo

  landscape:
    image: explorviz/explorviz-backend-landscape:latest
    container_name: explorviz-backend-landscape

  analysis:
    image: explorviz/explorviz-backend-analysis:latest
    container_name: explorviz-backend-analysis
    ports:
      - "10133:10133"

  discovery:
    image: explorviz/explorviz-backend-discovery:latest
    container_name: explorviz-backend-discovery
    ports:
      - "8083:8083"

  frontend:
    image: explorviz/explorviz-frontend:latest
    container_name: explorviz-frontend
    ports:
      - "8090:80"
    environment:
      - API_ROOT=http://localhost:8080

volumes:
  explorviz-auth-mongo-data:
  explorviz-auth-mongo-configdb:
