# Start ExplorViz with latest development changes
# Monitored applications can be connected

version: "3.2"
services:

  mongo:
    image: mongo
    container_name: explorviz-backend-auth-mongo
    volumes:
       - explorviz-auth-mongo-data:/data/db
       - explorviz-auth-mongo-configdb:/data/configdb

  authentication:
    image: explorviz/explorviz-backend-authentication:dev
    container_name: explorviz-backend-auth
    depends_on:
      - mongo
    environment:
      - MONGO_IP=mongo

  landscape:
    image: explorviz/explorviz-backend-landscape:dev
    container_name: explorviz-backend-landscape
    environment:
      - DUMMY_MODE=true

  analysis:
    image: explorviz/explorviz-backend-analysis:dev
    container_name: explorviz-backend-analysis

  discovery:
    image: explorviz/explorviz-backend-discovery:dev
    container_name: explorviz-backend-discovery

  frontend:
    image: explorviz/explorviz-frontend:dev
    container_name: explorviz-frontend
    ports:
      - "8090:80"
    environment:
      - API_ROOT=http://localhost:8090
    depends_on:
      - discovery
      - landscape
      - analysis
      - authentication

volumes:
  explorviz-auth-mongo-data:
  explorviz-auth-mongo-configdb:
